### PR TITLE
install fields and template

### PR DESCRIPTION
**Pull request by jmartsch**
as the title says

### CODE REVIEW

**Comment by mtwebit** [comment]
Thanks, it is really useful!
It does not work as it is (there are typos and the fg is broken) but I'll review the suggested code and merge the edited version.

**Comment by jmartsch** [comment]
Hmm, it works here, but thanks for taking a look at it and merging afterwards

**Comment by jmartsch** [comment]
After you merged, I will also create an uninstall method

**Comment by jmartsch** [comment]
Another thing before merging: It would be good if the fieldnames of progress and signature would be also prefixed with "task_"

**Comment by mtwebit** [comment]
prefixing vars is on my TODO list but postponed atm

**Pull request merged**
